[pytest]
addopts =
    --html=reports/html/report.html
    --self-contained-html
    --alluredir=reports/allure-results
    --browser chromium
    -v


testpaths = tests


python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Custom markers
markers =
    homepage: Homepage validation tests
    navigation: Book navigation tests
    consistency: Data consistency tests
    links: Broken link tests
    images: Product image tests